{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9fc49a8f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-a729620180fb>\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\python\\estimator\\model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\model_fn.py\", line 29, in <module>\n",
      "    from tensorflow.python.types import core\n",
      "ModuleNotFoundError: No module named 'tensorflow.python.types'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ModuleNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-a729620180fb>\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\python\\estimator\\model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\model_fn.py\", line 29, in <module>\n",
      "    from tensorflow.python.types import core\n",
      "ModuleNotFoundError: No module named 'tensorflow.python.types'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ModuleNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-a729620180fb>\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\examples\\tutorials\\mnist\\input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_core\\python\\estimator\\model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\model_fn.py\", line 29, in <module>\n",
      "    from tensorflow.python.types import core\n",
      "ModuleNotFoundError: No module named 'tensorflow.python.types'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ModuleNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\chunc\\anaconda3\\envs\\tensorflow_v1\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.examples.tutorials.mnist import input_data\n",
    "mnist_ = input_data.read_data_sets(\"/tmp/data/\", one_hot = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "id": "520eba91",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras.datasets import mnist\n",
    "\n",
    "#Importing data\n",
    "(x_train, y_train), (x_test, y_test) = mnist.load_data()\n",
    "image_vector_size = 28*28\n",
    "\n",
    "#Normalization\n",
    "x_train = x_train.astype(float) / 255.\n",
    "x_test = x_test.astype(float) / 255.\n",
    "\n",
    "#Flattening Feature\n",
    "x_train = x_train.reshape(x_train.shape[0], image_vector_size)\n",
    "x_test = x_test.reshape(x_test.shape[0], image_vector_size)\n",
    "\n",
    "#Converting Target variable from scaler to softmax class\n",
    "import keras\n",
    "num_classes = 10\n",
    "y_train = keras.utils.to_categorical(y_train, num_classes)\n",
    "y_test = keras.utils.to_categorical(y_test, num_classes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "id": "1f9d0a37",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Parameters\n",
    "learning_rate = 0.001\n",
    "training_epochs = 20\n",
    "N = 784\n",
    "n_hidden_1 = 392 # N/2\n",
    "n_hidden_2 = 196 # N/4\n",
    "n_input = N\n",
    "n_classes = 10\n",
    "batch_size = 100\n",
    "x = tf.placeholder(\"float\",[None,n_input])\n",
    "y = tf.placeholder(\"float\",[None,n_classes])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "id": "ec6b4e0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1st Hidden Layer\n",
    "weight_hidden_1 = tf.Variable(tf.random_normal([n_input,n_hidden_1]))\n",
    "bias_hidden_1   = tf.Variable(tf.random_normal([n_hidden_1]))\n",
    "output_hidden_1 = tf.nn.relu(tf.add(tf.matmul(x,weight_hidden_1),bias_hidden_1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "id": "b2057c3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#2nd Hidden Layer\n",
    "weight_hidden_2 = tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2]))\n",
    "bias_hidden_2   = tf.Variable(tf.random_normal([n_hidden_2]))\n",
    "output_hidden_2 = tf.nn.sigmoid(tf.add(tf.matmul(output_hidden_1,weight_hidden_2),bias_hidden_2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "id": "05f281ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Output Layer\n",
    "weight_output = tf.Variable(tf.random_normal([n_hidden_2,n_classes]))\n",
    "bias_output   = tf.Variable(tf.random_normal([n_classes]))\n",
    "final_output  = tf.matmul(output_hidden_2,weight_output) + bias_output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "id": "898deed1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Loss Function = (y - y_pred)^2 / size\n",
    "# loss = tf.reduce_mean(tf.math.squared_difference(y,tf.nn.softmax(final_output)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "id": "4b23bddc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Loss Function = (y - y_pred)^4/size\n",
    "# loss = tf.reduce_mean((y - tf.nn.softmax(final_output))**4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "id": "ee975da7",
   "metadata": {},
   "outputs": [],
   "source": [
    "loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(\n",
    "   logits = final_output, labels = y)) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "id": "27b395b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Error function\n",
    "error = tf.reduce_mean(tf.math.squared_difference(y,tf.nn.softmax(final_output)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "id": "9570001e",
   "metadata": {},
   "outputs": [],
   "source": [
    "activated_output = tf.nn.softmax(final_output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "id": "4aab93c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Optimizer\n",
    "optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)\n",
    "correct_prediction = tf.equal(tf.argmax(tf.nn.softmax(final_output), 1), tf.argmax(y, 1))\n",
    "accuracy = tf.reduce_mean(tf.cast(correct_prediction, \"float\"))         "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 142,
   "id": "fcfdffaf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "Model Accuracy: 0.5752\n",
      "1\n",
      "Model Accuracy: 0.7377\n",
      "2\n",
      "Model Accuracy: 0.7881\n",
      "3\n",
      "Model Accuracy: 0.8142\n",
      "4\n",
      "Model Accuracy: 0.8279\n",
      "5\n",
      "Model Accuracy: 0.8391\n",
      "6\n",
      "Model Accuracy: 0.8486\n",
      "7\n",
      "Model Accuracy: 0.8545\n",
      "8\n",
      "Model Accuracy: 0.8619\n",
      "9\n",
      "Model Accuracy: 0.8656\n",
      "10\n",
      "Model Accuracy: 0.8692\n",
      "11\n",
      "Model Accuracy: 0.8719\n",
      "12\n",
      "Model Accuracy: 0.8748\n",
      "13\n",
      "Model Accuracy: 0.8784\n",
      "14\n",
      "Model Accuracy: 0.8815\n",
      "15\n",
      "Model Accuracy: 0.8834\n",
      "16\n",
      "Model Accuracy: 0.885\n",
      "17\n",
      "Model Accuracy: 0.8864\n",
      "18\n",
      "Model Accuracy: 0.888\n",
      "19\n",
      "Model Accuracy: 0.8895\n",
      "Model Accuracy: 0.8895\n"
     ]
    }
   ],
   "source": [
    "#Brute Force Meathod - \n",
    "init = tf.global_variables_initializer()\n",
    "with tf.Session() as sess:\n",
    "    sess.run(init)    \n",
    "    for epoch in range(training_epochs):        \n",
    "        print(epoch)        \n",
    "        for i in range(100):            \n",
    "            sess.run(optimizer,feed_dict={\n",
    "                x: x_train,\n",
    "                y: y_train\n",
    "            }) \n",
    "        correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y, 1))       \n",
    "        accuracy = tf.reduce_mean(tf.cast(correct_prediction, \"float\")) \n",
    "        print(\"Model Accuracy:\", accuracy.eval({x: x_test, y: y_test}))\n",
    "    correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y, 1))       \n",
    "    accuracy = tf.reduce_mean(tf.cast(correct_prediction, \"float\")) \n",
    "    print(\"Model Accuracy:\", accuracy.eval({x: x_test, y: y_test}))    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "id": "8e06cddf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 164\n",
      "0\n",
      "Model Accuracy: 0.7407\n",
      "1\n",
      "Model Accuracy: 0.8181\n",
      "2\n",
      "Model Accuracy: 0.8579\n",
      "3\n",
      "Model Accuracy: 0.88\n",
      "4\n",
      "Model Accuracy: 0.8938\n",
      "5\n",
      "Model Accuracy: 0.9044\n",
      "6\n",
      "Model Accuracy: 0.912\n",
      "7\n",
      "Model Accuracy: 0.918\n",
      "8\n",
      "Model Accuracy: 0.9214\n",
      "9\n",
      "Model Accuracy: 0.9269\n",
      "10\n",
      "Model Accuracy: 0.9301\n",
      "11\n",
      "Model Accuracy: 0.9325\n",
      "12\n",
      "Model Accuracy: 0.9367\n",
      "13\n",
      "Model Accuracy: 0.9374\n",
      "14\n",
      "Model Accuracy: 0.941\n",
      "15\n",
      "Model Accuracy: 0.9428\n",
      "16\n",
      "Model Accuracy: 0.9433\n",
      "17\n",
      "Model Accuracy: 0.9473\n",
      "18\n",
      "Model Accuracy: 0.9468\n",
      "19\n",
      "Model Accuracy: 0.9508\n",
      "20\n",
      "Model Accuracy: 0.9511\n",
      "21\n",
      "Model Accuracy: 0.9521\n",
      "22\n",
      "Model Accuracy: 0.9534\n",
      "23\n",
      "Model Accuracy: 0.9533\n",
      "24\n",
      "Model Accuracy: 0.9539\n",
      "25\n",
      "Model Accuracy: 0.9565\n",
      "26\n",
      "Model Accuracy: 0.9556\n",
      "27\n",
      "Model Accuracy: 0.9545\n",
      "28\n",
      "Model Accuracy: 0.958\n",
      "29\n",
      "Model Accuracy: 0.9568\n",
      "30\n",
      "Model Accuracy: 0.9574\n",
      "31\n",
      "Model Accuracy: 0.9576\n",
      "32\n",
      "Model Accuracy: 0.9598\n",
      "33\n",
      "Model Accuracy: 0.9601\n",
      "34\n",
      "Model Accuracy: 0.9614\n",
      "35\n",
      "Model Accuracy: 0.9596\n",
      "36\n",
      "Model Accuracy: 0.9622\n",
      "37\n",
      "Model Accuracy: 0.9615\n",
      "38\n",
      "Model Accuracy: 0.9612\n",
      "39\n",
      "Model Accuracy: 0.9627\n",
      "40\n",
      "Model Accuracy: 0.9627\n",
      "41\n",
      "Model Accuracy: 0.9625\n",
      "42\n",
      "Model Accuracy: 0.9628\n",
      "43\n",
      "Model Accuracy: 0.9643\n",
      "44\n",
      "Model Accuracy: 0.9641\n",
      "45\n",
      "Model Accuracy: 0.963\n",
      "46\n",
      "Model Accuracy: 0.9633\n",
      "47\n",
      "Model Accuracy: 0.9642\n",
      "48\n",
      "Model Accuracy: 0.9656\n",
      "49\n",
      "Model Accuracy: 0.9667\n",
      "50\n",
      "Model Accuracy: 0.9659\n",
      "51\n",
      "Model Accuracy: 0.9661\n",
      "52\n",
      "Model Accuracy: 0.9649\n",
      "53\n",
      "Model Accuracy: 0.9647\n",
      "54\n",
      "Model Accuracy: 0.9651\n",
      "55\n",
      "Model Accuracy: 0.9637\n",
      "56\n",
      "Model Accuracy: 0.9657\n",
      "57\n",
      "Model Accuracy: 0.9661\n",
      "58\n",
      "Model Accuracy: 0.9656\n",
      "59\n",
      "Model Accuracy: 0.967\n",
      "60\n",
      "Model Accuracy: 0.9664\n",
      "61\n",
      "Model Accuracy: 0.9656\n",
      "62\n",
      "Model Accuracy: 0.9656\n",
      "63\n",
      "Model Accuracy: 0.9664\n",
      "64\n",
      "Model Accuracy: 0.9668\n",
      "65\n",
      "Model Accuracy: 0.968\n",
      "66\n",
      "Model Accuracy: 0.9679\n",
      "67\n",
      "Model Accuracy: 0.9677\n",
      "68\n",
      "Model Accuracy: 0.9677\n",
      "69\n",
      "Model Accuracy: 0.9679\n",
      "70\n",
      "Model Accuracy: 0.9687\n",
      "71\n",
      "Model Accuracy: 0.9673\n",
      "72\n",
      "Model Accuracy: 0.9677\n",
      "73\n",
      "Model Accuracy: 0.9667\n",
      "74\n",
      "Model Accuracy: 0.9673\n",
      "75\n",
      "Model Accuracy: 0.9687\n",
      "76\n",
      "Model Accuracy: 0.97\n",
      "77\n",
      "Model Accuracy: 0.9702\n",
      "78\n",
      "Model Accuracy: 0.9684\n",
      "79\n",
      "Model Accuracy: 0.9677\n",
      "80\n",
      "Model Accuracy: 0.9692\n",
      "81\n",
      "Model Accuracy: 0.9675\n",
      "82\n",
      "Model Accuracy: 0.9689\n",
      "83\n",
      "Model Accuracy: 0.9673\n",
      "84\n",
      "Model Accuracy: 0.9682\n",
      "85\n",
      "Model Accuracy: 0.972\n",
      "86\n",
      "Model Accuracy: 0.9689\n",
      "87\n",
      "Model Accuracy: 0.9705\n",
      "88\n",
      "Model Accuracy: 0.9701\n",
      "89\n",
      "Model Accuracy: 0.9705\n",
      "90\n",
      "Model Accuracy: 0.9709\n",
      "91\n",
      "Model Accuracy: 0.9703\n",
      "92\n",
      "Model Accuracy: 0.9705\n",
      "93\n",
      "Model Accuracy: 0.9707\n",
      "94\n",
      "Model Accuracy: 0.971\n",
      "95\n",
      "Model Accuracy: 0.9709\n",
      "96\n",
      "Model Accuracy: 0.9694\n",
      "97\n",
      "Model Accuracy: 0.9712\n",
      "98\n",
      "Model Accuracy: 0.9695\n",
      "99\n",
      "Model Accuracy: 0.9712\n",
      "Model Accuracy: 0.9712\n"
     ]
    }
   ],
   "source": [
    "#Graph starting\n",
    "init = tf.global_variables_initializer()\n",
    "mse_loss_list = []\n",
    "epoch_list = []\n",
    "with tf.Session() as sess:\n",
    "    \n",
    "    sess.run(init)    \n",
    "    for epoch in range(100):                  \n",
    "        \n",
    "        print(epoch)\n",
    "        avg_cost = 0. \n",
    "        total_batch = int(mnist_.train.num_examples / batch_size)             \n",
    "        for i in range(total_batch):             \n",
    "            batch_xs, batch_ys = mnist_.train.next_batch(batch_size)          \n",
    "            sess.run(optimizer, feed_dict = {\n",
    "            x: batch_xs, y: batch_ys})\n",
    "        \n",
    "        \n",
    "        correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y, 1))       \n",
    "        accuracy = tf.reduce_mean(tf.cast(correct_prediction, \"float\")) \n",
    "        print(\"Model Accuracy:\", accuracy.eval({x: x_test, y: y_test}))\n",
    "        \n",
    "        mse_loss_list.append(sess.run(error,feed_dict={\n",
    "            x: mnist_.test.images, y: mnist_.test.labels\n",
    "        }))\n",
    "        epoch_list.append(epoch+1)\n",
    "        \n",
    "    correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y, 1))       \n",
    "    accuracy = tf.reduce_mean(tf.cast(correct_prediction, \"float\")) \n",
    "    print(\"Model Accuracy:\", accuracy.eval({x: mnist_.test.images, y: mnist_.test.labels}))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "id": "ac443747",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 140,
   "id": "00336632",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 0, 'Epoch ->')"
      ]
     },
     "execution_count": 140,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAY4AAAEGCAYAAABy53LJAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAt6UlEQVR4nO3de3ycZZ338c8vk0zOh6Zp0zRtaZGUUkopJUCRdQWEtSBQXHWFRwVBRVZQ8HH3EV1fLq57UF6ijyjCgtYtrg8srq5UrGCtAgICbaEtLT2FHmjaNE3aNM35+Hv+mDtlmuYwUzOdJPN9v17zytz3fd0zv4tDfrkO93WZuyMiIhKrtGQHICIiY4sSh4iIxEWJQ0RE4qLEISIicVHiEBGRuKQnO4CToaSkxGfOnJnsMERExpS1a9fWu/uk/udTInHMnDmTNWvWJDsMEZExxcx2D3ReXVUiIhIXJQ4REYmLEoeIiMRFiUNEROKixCEiInFR4hARkbgocYiISFyUOIawanMtP3imKtlhiIiMKkocQ3huWx3//uyOZIchIjKqJDRxmNliM9tqZlVmdtcA183M7guubzCzhf2uh8zsNTN7MupcsZmtNLPtwc8JiYo/JzOdts6eRH28iMiYlLDEYWYh4H7gCmAucL2Zze1X7AqgInjdAjzQ7/odwOZ+5+4CVrl7BbAqOE6I3HCIzp5eunp6E/UVIiJjTiJbHOcDVe6+w907gceAJf3KLAEe8YiXgCIzKwMws2nA+4AfDnDPsuD9MuDaBMVPdjiylFerWh0iIkclMnGUA3uijquDc7GW+b/A/wH6/7lf6u41AMHPyQN9uZndYmZrzGxNXV3dCVUgNxwCoLWz+4TuFxEZjxKZOGyAcx5LGTO7Cjjg7mtP9Mvd/SF3r3T3ykmTjlsVOCbZRxOHWhwiIn0SmTiqgelRx9OAfTGWuQi4xsx2EeniutTM/jMoUxvVnVUGHBj50CNy+7qqOpQ4RET6JDJxrAYqzGyWmYWB64Dl/cosB24IZlctAhrdvcbdv+Tu09x9ZnDf7939o1H33Bi8vxF4IlEVyAlaHC3qqhIROSphGzm5e7eZ3Q48DYSApe6+ycxuDa4/CKwArgSqgFbgphg++hvA42b2CeAt4EOJiB8i03EBTckVEYmS0B0A3X0FkeQQfe7BqPcO3DbMZzwDPBN1fBB4z0jGORi1OEREjqcnx4eQo8FxEZHjKHEMIefo4LhaHCIifZQ4hnC0xdGlFoeISB8ljiFkpqeRZpqOKyISTYljCGZGbjhdYxwiIlGUOIaRHQ5pyRERkShKHMPIzVSLQ0QkmhLHMLIz1OIQEYmmxDGM3MyQWhwiIlGUOIaRHU6nRYlDROQoJY5h5IZDegBQRCSKEscwIrOq1OIQEemjxDGMyHMcanGIiPRR4hhGjlocIiLHUOIYRk44nY7uXnp6++96KyKSmpQ4hpGb2be0urqrRERAiWNY2dqTQ0TkGEocw8jt25NDiUNEBFDiGFZfi6NFz3KIiAAJThxmttjMtppZlZndNcB1M7P7gusbzGxhcD7LzF4xs/VmtsnMvhZ1z91mttfM1gWvKxNZh74WR5s2cxIRASA9UR9sZiHgfuByoBpYbWbL3f2NqGJXABXB6wLggeBnB3CpuzebWQbwvJn9xt1fCu77jrt/K1GxR1OLQ0TkWIlscZwPVLn7DnfvBB4DlvQrswR4xCNeAorMrCw4bg7KZASvpMyHfXtWlVocIiKQ2MRRDuyJOq4OzsVUxsxCZrYOOACsdPeXo8rdHnRtLTWzCQN9uZndYmZrzGxNXV3dCVciJ0OD4yIi0RKZOGyAc/1bDYOWcfced18ATAPON7N5wfUHgHcAC4Aa4N6BvtzdH3L3SnevnDRpUvzRB3L0HIeIyDESmTiqgelRx9OAffGWcffDwDPA4uC4NkgqvcDDRLrEEiZHz3GIiBwjkYljNVBhZrPMLAxcByzvV2Y5cEMwu2oR0OjuNWY2ycyKAMwsG7gM2BIcl0Xd/35gYwLrQFZ6CDO0tLqISCBhs6rcvdvMbgeeBkLAUnffZGa3BtcfBFYAVwJVQCtwU3B7GbAsmJmVBjzu7k8G1+4xswVEurR2AZ9OVB0A0tIs2D5WLQ4REUhg4gBw9xVEkkP0uQej3jtw2wD3bQDOGeQzPzbCYQ4rR7sAiogcpSfHY5ATDtGmwXEREUCJIyY54ZBaHCIiASWOGERaHEocIiKgxBGT3Mx0WtRVJSICKHHEJDtDLQ4RkT5KHDFQi0NE5G1KHDHIDodo7VCLQ0QElDhikhvWA4AiIn2UOGKQHU6nrauH3t6krOwuIjKqKHHEIDdY6FC7AIqIxJg4zCwj2Kb1vEQHNBrlZEZWZtEAuYhI7C2OJUAY+FQCYxm1cjKCFofGOUREYk4cnwBuBi42s5wExjMq9W0f26KZVSIiwycOM5sOTA72BP8l8OFEBzXaZIcjXVVtXeqqEhGJpcVxE/BI8P7HRFofKaVvcFwtDhGRYRKHmRnwUeAnAO6+GQiZ2eknIbZRI1vbx4qIHDVciyMfuNPdD0Wd+0wC4xmVcoOuqlbNqhIRGXoHQHc/QtQOfmY2xd1fS3hUo0xOX1eVWhwiInE/ALhi+CJvM7PFZrbVzKrM7K4BrpuZ3Rdc32BmC4PzWWb2ipmtN7NNZva1qHuKzWylmW0Pfk6Isw5x63uOQ7sAiojEnzgs5oJmIeB+4ApgLnC9mc3tV+wKoCJ43QI8EJzvAC5197OBBcBiM1sUXLsLWOXuFcCq4DihsjM0OC4i0ifexPFwHGXPB6rcfYe7dwKPEXmQMNoS4BGPeAkoMrOy4Lg5KJMRvDzqnmXB+2XAtXHWIW6hNCMrI01LjoiIEGficPcfxFG8HNgTdVwdnIupjJmFzGwdcABY6e4vB2VK3b0miKcGmBxHTCcsJ5xOS4e6qkREErnI4UDdWv2Xlx20jLv3uPsCYBpwvpnNi+vLzW4xszVmtqauri6eWwekfcdFRCISmTiqgelRx9OAffGWcffDwDPA4uBUrZmVAQQ/Dwz05e7+kLtXunvlpEmTTrAKb8sJh7TIoYgIwz8AGDKz353gZ68GKsxslpmFgeuA5f3KLAduCGZXLQIa3b3GzCaZWVEQQzZwGbAl6p4bg/c3Ak+cYHxxyQmn6wFAERGGf46jx8xazazQ3Rvj+WB37zaz24GngRCw1N03mdmtwfUHiUzvvRKoAlqJLG8CUAYsC2ZmpQGPu/uTwbVvAI+b2SeAt4APxRPXicrRLoAiIsAwiSPQDrxuZiuBlr6T7v654W509xX0e/YjSBh97x24bYD7NgDnDPKZB4H3xBD3iMoJp9PQ2nayv1ZEZNSJJXH8OniltEiLQ2McIiLDJg53XxaMUcwOTm11967EhjX65GaG9ACgiAgxJA4zu5jIg3a7iEyfnW5mN7r7cwmNbJTJzkjXkiMiIsTWVXUv8FfuvhXAzGYDjwLnJjKw0SYvM0RrVw89vU4oLeaVV0RExp1YnuPI6EsaAO6+jcgSICmlODeMOzS0diY7FBGRpIqlxbHWzH5EsJkT8BFgbeJCGp1K8jMBqG/uoCQvM8nRiIgkTywtjluBTcDngDuAN4JzKaUvWdQ3qcUhIqltyBaHmaUBa919HvDtkxPS6FSSFwbgYEtHkiMREUmuIVsc7t4LrDezGScpnlGrr8VR16TEISKpLZYxjjJgk5m9wrFPjl+TsKhGocLsDDJCRn2zuqpEJLXFkji+NnyR8c/MmJibycFmtThEJLXFMsZxfzDGkfIm5oWpV+IQkRSnMY44lORlqqtKRFKexjjiUJKXyfbapmSHISKSVBrjiENJXpj65k7cHTMtOyIiqWnQxGFmc9x9i7s/a2aZ7t4RdW3RyQlvdCnJy6Szp5cj7d0UZqfcqisiIsDQYxz/L+r9n/pd+0ECYhn1SvIjDwFqgFxEUtlQicMGeT/QcUroewjwoAbIRSSFDZU4fJD3Ax2nhIm5by90KCKSqoZKHNPM7D4z+17U+77j8lg+3MwWm9lWM6sys7sGuG7BZ1aZ2QYzWxicn25mfzCzzWa2yczuiLrnbjPba2brgteVcdb5hKmrSkRk6FlVfx/1fk2/a/2Pj2NmIeB+4HKgGlhtZsvd/Y2oYlcAFcHrAuCB4Gc38AV3f9XM8oks7b4y6t7vuPu3hothpBXnhDFDz3KISEobNHG4+7I/87PPB6rcfQeAmT0GLCGyLHufJcAj7u7AS2ZWZGZl7l4D1ARxNJnZZiKtnDdIovRQGhNy9PS4iKS2WPbjOFHlwJ6o42qO7+IatoyZzQTOAV6OOn170LW11MwmDPTlZnaLma0xszV1dXUnWIXjleSFqdcKuSKSwhKZOAaaedV/UH3IMmaWB/wcuNPdjwSnHwDeASwg0iq5d6Avd/eH3L3S3SsnTZoUZ+iDK8nL5GCLuqpEJHUlMnFUA9OjjqcB+2ItY2YZRJLGT939F30F3L3W3XuCdbQeJtIldtJE1qtSi0NEUtewicPMZpvZKjPbGBzPN7OvxPDZq4EKM5tlZmHgOmB5vzLLgRuC2VWLgEZ3r7HIeh4/Aja7+zE7D5pZWdTh+4GNMcQyYiaqq0pEUlwsLY6HgS8BXQDuvoFIEhiSu3cDtwNPA5uBx919k5ndamZ9e5avAHYAVcH3fCY4fxHwMeDSAabd3mNmr5vZBuAS4PMx1GHElORl0tLZQ1tnz8n8WhGRUSOWRQ5z3P2Vfov6dcfy4e6+gkhyiD73YNR7B24b4L7nGeTpdHf/WCzfnSiT8t5+CHB6cU4yQxERSYpYWhz1ZvYOgkFrM/sgwVTZVDQxTw8Bikhqi6XFcRvwEDDHzPYCO4GPJDSqUUzrVYlIqhtu69gQ8LfufpmZ5QJp7p7SOxmV5Gu9KhFJbUMmDnfvMbNzg/ctQ5VNFRNz1VUlIqktlq6q18xsOfAzjt069heD3zJ+ZWWEyM9M13pVIpKyYkkcxcBB4NKocw6kZOKASHeVWhwikqqGTRzuftPJCGQsiew9rsQhIqlp2MRhZj9mgI2b3P3mhEQ0BkzMzaSqrjnZYYiIJEUsXVVPRr3PIrLMR/81p1JKSX6Yl3eqxSEiqSmWrqqfRx+b2aPA7xIW0RhQkpdJQ2sXXT29ZIQSuU6kiMjocyK/9SqAGSMdyFgytTAbgL0NbUmORETk5ItljKOJyBiHBT/3A19McFyjWkVpHgBba5uYWZKb5GhERE6uWLqq8k9GIGPJ7NLIP5Kt+5t475lTkhyNiMjJFcvgOMH2rBVEBscBcPfnEhXUaJebmc6M4hy21qb06isikqJi6ar6JHAHkd351gGLgD9x7AOBKWd2aT5b9ytxiEjqiWVw/A7gPGC3u18CnAPUJTSqMWDOlHx21rfQ0a0NnUQktcSSONrdvR3AzDLdfQtwemLDGv1On5JPT6/z5gGt/SgiqSWWxFFtZkXAL4GVZvYEKf4AIEQSB8DW2iNJjkRE5OSKZVbV+4O3d5vZH4BC4KmERjUGzCrJJSNkbNE4h4ikmGFbHGZW3PcCXgeeB/Kizg1172Iz22pmVWZ21wDXzczuC65vMLOFwfnpZvYHM9tsZpvM7I5+8aw0s+3Bzwlx13oEZITSeMekPLYpcYhIiomlq+pVIoPh24Dtwfu1wWvNYDcFuwfeD1wBzAWuN7O5/YpdQWSabwVwC/BAcL4b+IK7n0FkFtdtUffeBaxy9wpgVXCcFKdP0cwqEUk9sSSOp4Cr3b3E3ScCVwG/cPdZ7n7qEPedD1S5+w537wQeA5b0K7MEeMQjXgKKzKzM3Wvc/VWAYKvazUB51D3LgvfLgGtjqENCnD4ln32N7TS2dSUrBBGRky6WxHGeu6/oO3D33wDvjuG+cmBP1HE1b//yj7mMmc0kMgX45eBUqbvXBLHUAJMH+nIzu8XM1pjZmrq6xMwenhMMkG/Xg4AikkJiSRz1ZvYVM5tpZqeY2T8Q2RFwODbAuf77egxZxszygJ8Dd7p7XNOX3P0hd69098pJkybFc2vM+pYe0QC5iKSSWBLH9cAk4H+ITMmdHJwbTjUwPep4GsdP4x20jJllEEkaP+23v3mtmZUFZcqAAzHEkhDlRdnkZ6ZrnENEUsqwicPdD7n7He5+DpFlRu5090MxfPZqoMLMZplZGLgOWN6vzHLghmB21SKg0d1rzMyAHwGb3f3bA9xzY/D+RuCJGGJJCDNj9pR8rVklIill0MRhZl81sznB+0wz+z1QReQv/suG+2B37wZuB54mMrj9uLtvMrNbzezWoNgKYEfwuQ8DnwnOXwR8DLjUzNYFryuDa98ALjez7cDlwXHS9K1Z5X7c7roiIuPSUA8Afhj4evD+RiJJZjIwm8hspmF3AQwG1Vf0O/dg1HsHbhvgvucZePwDdz8IvGe47z5Z5kzJ59FX3qKmsZ2pRdnJDkdEJOGG6qrq9Lf/jH4v8Ki797j7ZmJcjj0VnDOjCIA1uxuSG4iIyEkyVOLoMLN5ZjYJuAT4bdS1nMSGNXbMLSsgLzOdl3fEMtFMRGTsG6rlcAfw30RmVH3H3XcCBGMNr52E2MaE9FAalTMn8JISh4ikiEETh7u/DMwZ4Pxx4xapbtGpE3lmax11TR1Mys9MdjgiIgkVy3McMowLZkXWenx5p1odIjL+KXGMgHnlheSGQ7y8I5bHW0RExjYljhGQEUrj3JnFGucQkZQQ07RaM3snMDO6vLs/kqCYxqRFpxZzz1NbOdjcwcQ8jXOIyPg1bOIws58A7wDWAT3BaQeUOKJcMGsiAK/sPMQVZ5UlORoRkcSJpcVRCcx1rakxpPnTCsnOCPHSjoNKHCIyrsUyxrERmJLoQMa6jOB5jpd3aoBcRMa3WBJHCfCGmT1tZsv7XokObCy6YFYxW/Y3cailM9mhiIgkTCxdVXcnOojx4qLTSvjWb7fxhy0H+MC505IdjohIQgybONz92ZMRyHiwYHoR5UXZPLlhnxKHiIxbw3ZVmdkiM1ttZs1m1mlmPWYW1zauqcLMuOrsMv64vZ4GdVeJyDgVyxjH94lsFbsdyAY+GZyTAVw9fyrdvc5Tm/YnOxQRkYSI6clxd68CQsF+HD8GLk5oVGPYmVMLOLUkl1+t77+9uojI+BBL4mgN9gxfZ2b3mNnngdwExzVmmRlXzS/jpR0HOdDUnuxwRERGXCyJ42NBuduBFmA68IFYPtzMFpvZVjOrMrO7BrhuZnZfcH2DmS2MurbUzA6Y2cZ+99xtZnsH2It81Lj67Kn0OvzmdXVXicj4M2zicPfdRPb/LnP3r7n7/w66roZkZiHgfuAKYC5wvZnN7VfsCqAieN0CPBB17T+AxYN8/HfcfUHwGnV7g1SU5jNnSr66q0RkXIplVtXVRNapeio4XhDjA4DnA1XuvsPdO4HHgCX9yiwBHvGIl4AiMysDcPfngDH7GPbVZ09lze4Gqhtakx2KiMiIiqWr6m4iSeAwgLuvI7JS7nDKgT1Rx9XBuXjLDOT2oGtrqZlNGKiAmd1iZmvMbE1dXV0MHzmyrjl7Khkh497fbjvp3y0ikkixJI5ud288gc+2Ac71XygxljL9PUBktd4FQA1w70CF3P0hd69098pJkyYN85Ejb3pxDre++x38z2t7ebGq/qR/v4hIosS0yKGZ/S8gZGYVZvY94MUY7qsmMpDeZxrQv9M/ljLHcPfaYFpwL/AwkdbQqHTbJadxysQcvvLLjXR09wx/g4jIGBBL4vgscCbQATwKHAHujOG+1UCFmc0KpvNeB/QfG1kO3BDMrloENLp7zVAf2jcGEng/kdV7R6WsjBD/tGQeO+pbePCZHckOR0RkRMSyVlUr8A/BK2bu3m1mtwNPAyFgqbtvMrNbg+sPAiuAK4EqoBW4qe9+M3uUyIOGJWZWDfyju/8IuMfMFhDp0toFfDqeuE62d8+exFXzy7j/mSquWTCVWSV6BEZExjYbbH+m4WZOufs1CYkoASorK33NmjVJ+/4DR9q59N5nWXRqMT+88bykxSEiEg8zW+vulf3PD9XiuJDIjKdHgZcZeCBbYjC5IIvbLjmNbz61hT9ur+NdFSd/sF5EZKQMNcYxBfgyMA/4LnA5UO/uz2qp9fjd/BczmVGcw9effIPunt5khyMicsIGTRzBzKWn3P1GYBGRcYhnzOyzJy26cSQzPcSXrzyDbbXN/L9X3kp2OCIiJ2zIWVVmlmlmfw38J3AbcB/wi5MR2Hj03jNLufDUiXx75TYaW7uSHY6IyAkZNHGY2TIiz2ssBL7m7ue5+9fdfe9Ji26cMTO+evVcjrR18ZUnNjLYxAQRkdFsqBbHx4DZwB3Ai2Z2JHg1aQfAE3dGWQFf+KvT+dX6fTzyp93JDkdEJG6Dzqpy95g2eZL4/e2738Gruxv451+/wVnTClk4Y8DltkRERiUlhyRISzO+/TcLmFKYxW0/fZWDzR3JDklEJGZKHElSmJPBAx85l4MtnXx1+aZkhyMiEjMljiSaV17IbRefxq831PCCVtAVkTFCiSPJPv3uU5lRnMNXn9hIZ7ceDBSR0U+JI8myMkLcfc1c3qxrYekLO5MdjojIsJQ4RoFL55Ry2Rml3LdqOzWNbckOR0RkSEoco8Q/Xj2Xnl7n1p+s5VBLZ7LDEREZlBLHKDG9OIfvXX8Om/c38aEHX2TvYbU8RGR0UuIYRf7qzCk8cvP5HDjSwQcfeJE39ukBfREZfZQ4RplFp07kvz59Id29zlXf+yN/97P17DnUmuywRESOUuIYheZOLeDpO/+Smy+axfL1+7j03mf4wTNVyQ5LRARQ4hi1inPDfOWquTz79xdz2Rml3PPUVpav35fssEREEps4zGyxmW01syozu2uA62Zm9wXXN5jZwqhrS83sgJlt7HdPsZmtNLPtwc9xvUJgWWE2373uHCpPmcAX/3sDm2s07iEiyZWwxGFmIeB+4ApgLnC9mc3tV+wKoCJ43QI8EHXtP4DFA3z0XcAqd68AVgXH41o4PY0ffHQhBdnpfPonazncqum6IpI8iWxxnA9UufsOd+8EHgOW9CuzBHjEI14CisysDMDdnwMODfC5S4BlwftlwLWJCH60mZyfxQMfPZeaxjbed9/zfPbR1/j+77fz6lsNyQ5NRFJMIhNHObAn6rg6OBdvmf5K3b0GIPg5eaBCZnaLma0xszV1dXVxBT5aLZwxgQc+ci5zpuTz2lsNfOu32/jrH7zIP/3qDTq6e5IdnoikiEE3choBNsC5/nulxlLmhLj7Q8BDAJWVleNmj9bL5pZy2dxSAI60d3Hv01tZ+sJOXnyznu9dfw4VpflJjlBExrtEtjiqgelRx9OA/tOCYinTX21fd1bw88CfGeeYVZCVwdeWzGPpxyupa+rg2vtfYO3ugXr3RERGTiITx2qgwsxmmVkYuA5Y3q/McuCGYHbVIqCxrxtqCMuBG4P3NwJPjGTQY9Glc0r59efexeSCLG5cuprXNO4hIgmUsMTh7t3A7cDTwGbgcXffZGa3mtmtQbEVwA6gCngY+Ezf/Wb2KPAn4HQzqzazTwSXvgFcbmbbgcuD45Q3pTCLRz+1iIl5YW740Sus33M42SGJyDhl7uOm+39QlZWVvmbNmmSHcVLsO9zGhx/6E9UNbZTmZzG9OJs5Uwr4wl/NpignnOzwRGQMMbO17l7Z/7yeHB9nphZl87NPv5M73lPBRaeVYGY8tvot3v+DF3mzrjnZ4YnIOKAWRwpYs+sQn/7JWrp6ern3bxYwMS9MdUMbrR3dXLNgKjnhRE6uE5GxarAWhxJHithzqJVPPbKGLfubjjl/9rRCfvTx8yjJy0xSZCIyWilxpHjiAGju6GblG/spzM6gvCiHHXXNfP7xdZQWZLHspvOZWZKb7BBFZBRR4lDiGNCrbzXwyWWRfzafv3w2f31OObmZ6roSESUOJY4h7Kxv4c7HXmN9dSP5Wel8YOE0CrLSqWvuoKGliyvnl3H1/DLMBnrQX0TGKyUOJY4huTuvvnWYZS/uYsXrNfS4MzE3k4yQUdPYzhXzpvDP185jQk6Y1/Y0sPKNA0ybkM2HKqeRmR5KdvgikgBKHEocMWvv6iE9zUgPpdHT6zz03A6+s3IbeVnpZISM2iMdhNKMnl6nrDCLz1xyGn+jBCIy7ihxKHH8Wbbub+JfVmwmKz2N980v49I5k9lQ3ch3Vm5jze4GTi3J5Z4PzqdyZvHRe3bUNbNuz2GOtHVxpL2bKYVZfHDhNNLS1OUlMhYocShxJIS788y2Or7yPxvZ19jGTe+cxXkzJ/CfL+/mhaqDx5V/75ml3Ps3C8jLTKezu5efvLSb32+pZebEXOaUFXB6aT7TJmQzOT+T9JCeTxVJJiUOJY6Eau7o5pu/2cJPXtoNwNTCLD6y6BTee+YUinPD5Gels+zFXfzbb7YwqySXmy+axb8/9ya7D7Zy2uQ8ao+009TeffTzQmnGjOIcbn33qXzo3OlqpYgkgRKHEsdJsX7PYQ61dvKu00oGbDG8WFXP7Y++xqGWTmaX5vHlK8/g4tMn4+7UNLazrbaJfYfb2Xu4lRffPMhrbx3m7GmFfPXqM6kozcMd0tNswCnDR9q7yA2nE1KSERkRShxKHKPGvsNtbKg+zGVnlA7ZHeXu/HLdXv51xRbqmjqOufa+s8r48vvOoLwom47uHv792R18/w9VVEzO45sfmM+88sJjynf19LJ+z2Fe2nGQUybmcvXZUxNSN5HxRIlDiWPMamrv4pfr9tHRFdket66pg2V/2gXAjRfOZOUbteyob+GyMyazbk8jDa2dfOpdp7JgehEb9zayYW8ja3cdoqXz7e11rz9/Ondfc6ZmgokMQYlDiWNcqW5o5V9+vZnfbNzPjOIcvn7tPN49exKNrV3864rN/NeayFb2oTSjYnIe554ygYtOK+H8WcX8+IWd3P+HN1kwvYjbLzmNDdWHWb2rgdoj7RTmZFCUnUFxbiZTCjOZUpDF9OIczj1lAvlZGYPG09DSyXPb6/jDlgOsfauB+eVFXHlWGZfMmaRFJGXMUuJQ4hiXttU2MaM4h6yMY1sOm/Y10tndyxllBcddA3hqYw1feHw9LZ09pBnMnVrAKcW5NLZ10dDaycHmTuqaO+jpjfz/EUoz5k8rZNGpE5lbVsCcKfkU5YRZtbmWX23Yx5/ePEivQ3FumIUzJrBuz2HqmzvIykhj8ZlT+FDldC48deKID/K7O72OxnUkIZQ4lDikn+qGVnYfbOXs6UXkDTDY3tPr1Dd3UHWgmRffrOfFNw+yobrxaDLpM3NiDu+bX8blc6dwVnnh0YcjV+86xJMb9rF83T6OtHczbUI21y4o55oFU5ldmj9oXN09vbxZ18KG6sM0tHaSmR4iKyONjFAaaWaYQX1zJ6/ubmDt7gYOtnQwt6yAc2ZMYO7UAopzwhRkZ5CdEaKpo4sjbV10dPdy3sxiphZlD/qdW/Y3kRMOUT4h+2gXXk+v09DaSUFWBuF0TY9ONUocShwyAtq7enizrpmt+5uoPdLBuypKOHNqwZDreLV39fDbN2r52Zo9vFBVT6/DnCn5zC7NJyOURjg9jbbObg62RFo6O+tbaOvqGfTz+pQXZXPuKRMoLcjk9b2NbKhupLVz6PvOKCvgL2eXMCEnTMiM7l5n7e4GXt5xkKaOyHRoM5icn0l3j3OotRN3CKencVZ5IQtnFDGvvJDZpfnMKskdsDUXr95eZ/+RdopyMsgJp9Pb6zxfVc9/rd7D7zbXclZ5IUvOKeeqs8qYkBvfLpbuTnVDG6++1UBGKI1LTp9Mdnj4mA82d7B2dwNnlhdSPkiyTQVJSRxmthj4LhACfuju3+h33YLrVwKtwMfd/dWh7jWzu4FPAXXBx3zZ3VcMFYcSh4wWB5raWbGhhhUb91PX1EFndy8d3b3khEMU54aZmBtmenEOZ08v5KzyIqYUZtHR1UN7dy9d3b040OtOfmY6kwuyjvns7p5eqhvaONLexZG2blo7u8nPyqAgO9KaeqGqnt9tPsDa3Q3HtJpmFOdw0WklLDq1mJ5eZ8+hNvY0tBJOT6MkL5PinAz2Hm7j1bcO8/reSBcgQJrBzIm5nD4lnzlTCsjMSGN7bTNVB5o40t7NpLxMJuVnUpSTcbSlFEozcsPp5GSG6Op2XtsTaTX1PcOTn5lORnoah1o6mZCTweVzS1m35zDbaptJTzPmTi1g/rRC5k8rYsH0It4xKW/AbrqaxjbuW1XF7zbXHjMjLzcc4r3zpjBnSj7baiN/AHT19HLlWWVcu6Cc/Kx0HvrjDpa9uOtoEi4vyuai0ybypSvOOCZxuTvrqxuZVZJLYfbg419j2UlPHGYWArYBlwPVwGrgend/I6rMlcBniSSOC4DvuvsFQ90bJI5md/9WrLEocYi8raunl66e3qPJY6hB//46unvYWd/C9tpmttc2sbW2ia37m9h9qBX3SEtldmk+RTkZ1DV1UNfUQWNbF73uONDT47R0dtOXtyom51E5s5i5Uwtobu+m9kg7R9q7uHTOZC6fW0pmegh3Z3NNE79+fR+v7j7Mxr2NR1tHeZnpzJ9WyLzyQuZMyadicj6/fr2GH7+wE3e44qwpVM4sZuGMIhrbunjitX2seL2Gpo5uSvIyOaMsn47uXl7ZeQiAzPQ0Ont6uXr+VD583nS21Taxetchfrf5ADOKc3jk5vOZWpRNS0c3f/ez9fxm437CoTQunTOZq8+eyoScDNq6emjr6iHNjIxQGhkhozg3TGlBFiV5mccluqb2LqoONNPR3UtJXpiJuZFkO1grtq2zh2e31bGjvpkLT53I2dOKEvaAbDISx4XA3e7+3uD4SwDu/m9RZf4deMbdHw2OtwIXAzMHu1eJQ2T0ae3spqvHY/rL293p6O6l1/2EZpz19jo7D7aw7q3DrNsTeW3d30RnT6QlZAbXLijnf18+m+nFOcfd39HdQ0tHD8VRrYe9h9tYvm4f+w63ccOFp1DRbwzqpR0H+dSyNeRlpfOv7z+Lbz61hW21TXz20gqOtHfxq/U11Dd39P+q46QZFGZnkJeVTm44ncOtXew/0n5cuXB6GtMmZDN9Qg6T8zPJSE8jHEqjprGNZ7fV0d7Ve7RsSV6YylOKae/uoaGlk5bOHk6blMe88gLOnFrIwlMmnHCLKBmJ44PAYnf/ZHD8MeACd789qsyTwDfc/fngeBXwRSKJY8B7g8TxceAIsAb4grs3DPD9twC3AMyYMePc3bt3J6SeIpJ83T297KxvYcv+Jk6bnMcZZQUj/h1v7DvCjT9+hbqmDgqzM/j+/zqHd1VMOvr966sP093jZGWEyMoI4Thd3U5nTy+HWjqpPdJO7ZF2Drd20dzRTVN7F/lZGVSU5lExOZ+ccIj65g4ONney/0g7ew61sqehlfqmTrp7e+nqcfIy03nPGZNZfOYUZk/J54WqelZtPsDreyN76UzICRNOT2N7bRO7DrYCsPTjlVw6p/SE6jxY4kjkBPOB2k79s9RgZYa69wHg68Hx14F7gZuPK+z+EPAQRFocsYUsImNReiiNitL841oKI2nu1AJ+fus7+eHzO/jEX8zilIlvb7WcHkrj3FOKh7g7MZYsKGfJgvIBrzW1d/HGviOcMXXkk2giE0c1MD3qeBqwL8Yy4cHudffavpNm9jDw5MiFLCIyuBkTc/inJfOSHUZM8rMyuODUiQn57EROzF4NVJjZLDMLA9cBy/uVWQ7cYBGLgEZ3rxnqXjMri7r//cDGBNZBRET6SViLw927zex24GkiU2qXuvsmM7s1uP4gsILIjKoqItNxbxrq3uCj7zGzBUS6qnYBn05UHURE5Hh6AFBERAY02OC41hAQEZG4KHGIiEhclDhERCQuShwiIhIXJQ4REYlLSsyqMrM6IJ41R0qA+gSFM5qlYr1Tsc6QmvVOxTrDn1fvU9x9Uv+TKZE44mVmawaagjbepWK9U7HOkJr1TsU6Q2Lqra4qERGJixKHiIjERYljYA8lO4AkScV6p2KdITXrnYp1hgTUW2McIiISF7U4REQkLkocIiISFyWOfsxssZltNbMqM7sr2fEkgplNN7M/mNlmM9tkZncE54vNbKWZbQ9+Tkh2rCPNzEJm9lqwbXGq1LnIzP7bzLYE/84vHO/1NrPPB/9tbzSzR80sazzW2cyWmtkBM9sYdW7QeprZl4LfbVvN7L0n+r1KHFHMLATcD1wBzAWuN7O5yY0qIbqJ7NV+BrAIuC2o513AKnevAFYFx+PNHcDmqONUqPN3gafcfQ5wNpH6j9t6m1k58Dmg0t3nEdnT5zrGZ53/A1jc79yA9Qz+H78OODO45wfB77y4KXEc63ygyt13uHsn8BiwJMkxjTh3r3H3V4P3TUR+kZQTqeuyoNgy4NqkBJggZjYNeB/ww6jT473OBcBfAj8CcPdOdz/MOK83kU3qss0sHcghsvX0uKuzuz8HHOp3erB6LgEec/cOd99JZAO980/ke5U4jlUO7Ik6rg7OjVtmNhM4B3gZKA227iX4OTmJoSXC/wX+D9AbdW681/lUoA74cdBF90Mzy2Uc19vd9wLfAt4CaohsSf1bxnGd+xmsniP2+02J41g2wLlxO1/ZzPKAnwN3uvuRZMeTSGZ2FXDA3dcmO5aTLB1YCDzg7ucALYyPLppBBX36S4BZwFQg18w+mtyoRoUR+/2mxHGsamB61PE0Ik3cccfMMogkjZ+6+y+C07VmVhZcLwMOJCu+BLgIuMbMdhHpgrzUzP6T8V1niPw3Xe3uLwfH/00kkYznel8G7HT3OnfvAn4BvJPxXedog9VzxH6/KXEcazVQYWazzCxMZCBpeZJjGnFmZkT6vDe7+7ejLi0Hbgze3wg8cbJjSxR3/5K7T3P3mUT+vf7e3T/KOK4zgLvvB/aY2enBqfcAbzC+6/0WsMjMcoL/1t9DZBxvPNc52mD1XA5cZ2aZZjYLqABeOZEv0JPj/ZjZlUT6wkPAUnf/l+RGNPLM7C+APwKv83Z//5eJjHM8Dswg8j/fh9y9/8DbmGdmFwN/5+5XmdlExnmdzWwBkQkBYWAHcBORPxrHbb3N7GvAh4nMIHwN+CSQxzirs5k9ClxMZOn0WuAfgV8ySD3N7B+Am4n8c7nT3X9zQt+rxCEiIvFQV5WIiMRFiUNEROKixCEiInFR4hARkbgocYiISFyUOERiZGY9ZrYu6jViT2Cb2czoFU5FRrP0ZAcgMoa0ufuCZAcRzcwmuHtDsuOQ1KIWh8ifycx2mdk3zeyV4HVacP4UM1tlZhuCnzOC86Vm9j9mtj54vTP4qJCZPRzsI/FbM8uO4et/aWbLzeyaYCVYkYRT4hCJXXa/rqoPR1074u7nA98nsvIAwftH3H0+8FPgvuD8fcCz7n42kXWjNgXnK4D73f1M4DDwgRhiuhi4Nyi7xcz+rS9xiSSKnhwXiZGZNbt73gDndwGXuvuOYPHI/e4+0czqgTJ37wrO17h7iZnVAdPcvSPqM2YCK4PNdzCzLwIZ7v7PccRXAHwxeH3Y3X9+4rUVGZyatiIjwwd5P1iZgXREve8BjumqCnZr61sWfrm7fzU4nw28n8gaREVEdjlcGVPUIidAXVUiI+PDUT//FLx/kchKvAAfAZ4P3q8C/haO7oFeEMsXuHuPuy8IXn1J4x4iq91eBPy9u1e6+/3jfX8VSS61OERil21m66KOn3L3vim5mWb2MpE/xq4Pzn0OWGpmf09kF76bgvN3AA+Z2SeItCz+lshOdSfiGeCr7t5+gveLxE1jHCJ/pmCMo9Ld65Mdi8jJoK4qERGJi1ocIiISF7U4REQkLkocIiISFyUOERGJixKHiIjERYlDRETi8v8BY34h4rOyUpMAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.plot(epoch_list,mse_loss_list)\n",
    "plt.ylabel(\"Mean Sqaure Error ->\")\n",
    "plt.xlabel(\"Epoch ->\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c579530",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
